trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
# Build
- job: Build
  pool:
    vmImage: 'windows-2019'
  steps:
  - powershell: ./build.ps1
    displayName: 'Build'
  - publish: $(Build.SourcesDirectory)/BuildArtifacts/Packages/NuGet
    artifact: NuGet Package
    displayName: 'Publish NuGet package as build artifact'
# Integration Tests Windows (.NET Framework runner)
- job: Test_Windows_DotNetFramework
  displayName: 'Integration Tests Windows (.NET Framework runner)'
  dependsOn: Build
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install NodeJs 14.x'
  - powershell: choco install markdownlint-cli --no-progress
    displayName: 'Install required tools'
  - download: current
    artifact: NuGet Package
    displayName: 'Download build artifact'
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Pipeline.Workspace)/NuGet Package
      targetFolder: $(Build.SourcesDirectory)/BuildArtifacts/Packages/NuGet
    displayName: 'Prepare build artifact for test run'
  - powershell: ./build.ps1 -target Build-Demo-Reports
    displayName: 'Run integration tests'
# Integration Tests macOS 10.14 (.NET Framework runner)
- job: Test_macOS_DotNetFramework
  displayName: 'Integration Tests macOS 10.14 (.NET Framework runner)'
  dependsOn: Build
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install NodeJs 14.x'
  - bash: |
      npm install -g markdownlint-cli
    displayName: 'Install required tools'
  # To manually select a Xamarin SDK version on the Hosted macOS agent, enable this script with the SDK version you want to target
  #  https://go.microsoft.com/fwlink/?linkid=871629 
  - bash: |
      sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1
    displayName: 'Select Mono 5.18.1'
  - download: current
    artifact: NuGet Package
    displayName: 'Download build artifact'
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Pipeline.Workspace)/NuGet Package
      targetFolder: $(Build.SourcesDirectory)/BuildArtifacts/Packages/NuGet
    displayName: 'Prepare build artifact for test run'
  - bash: |
      ./build.sh --target Build-Demo-Reports
    displayName: 'Run integration tests'